### ISSUE TITLE
Failed to load the toolbar package

### ISSUE THREAD

**Issue by TouPye** [suda/toolbar#27] opened 2015-04-21 08:29 UTC
I just updated this package to the latest version, and here is what happens :

**Atom Version**: 0.192.0
**System**: Microsoft Windows 8.1
**Thrown From**: [toolbar](https://github.com/suda/toolbar) package, v0.0.14

### Stack Trace

Failed to load the toolbar package

```
At variable @ui-tab-height is undefined in C:\Users\Pierre\.atom\packages\toolbar\styles\toolbar.less:22:16

LessError: variable @ui-tab-height is undefined
  at C:\Users\Pierre\.atom\packages\toolbar\styles\toolbar.less:22:16
```

**Comment by jerone** [comment] 2015-04-21 09:12
Ref: https://github.com/suda/toolbar/blob/d2696c6ae1e04f7bbe9cb720eeb7c038b5469e24/styles/toolbar.less#L22

This has been fixed in https://github.com/suda/toolbar/commit/c822d1b41e5a0afe66a0194e066809a2495df11d. Waiting for @suda to release a new version of Toolbar.

I'm still wondering why that happened. What themes do you have active?

**Comment by TouPye** [comment] 2015-04-21 09:18
UI Theme : [Flatland Dark](https://atom.io/themes/flatland-dark)

**Comment by jerone** [comment] 2015-04-21 09:22
[**@TouPye**](https://github.com/TouPye) commented on [21 apr. 2015 11:18 CEST](https://github.com/suda/toolbar/issues/27#issuecomment-94717065 "2015-04-21T09:18:20Z - Replied by Github Comment Enhancer"):
> UI Theme : [Flatland Dark](https://atom.io/themes/flatland-dark)

Did you mean [Flatland Dark UI Theme](https://atom.io/themes/flatland-dark-ui), because your linked theme is a syntax theme.

**Comment by TouPye** [comment] 2015-04-21 09:25
Yes indeed, sorry.

**Comment by jerone** [comment] 2015-04-21 09:38
Thnx.

Confirmed that `@ui-tab-height` was **only** part of [one-light-ui](https://github.com/atom/one-light-ui) and [one-dark-ui](https://github.com/atom/one-dark-ui) and missing from  [Flatland Dark UI Theme](https://atom.io/themes/flatland-dark-ui).

Confirmed that the current source code works with  [Flatland Dark UI Theme](https://atom.io/themes/flatland-dark-ui).

**Closed** 2015-04-21 15:16 UTC
